# Generated by Django 5.2 on 2025-04-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('tipo_servicio', models.CharField(choices=[('fumigacion_general', 'Fumigación General'), ('control_plagas', 'Control de Plagas'), ('desinfeccion', 'Desinfección'), ('control_termitas', 'Control de Termitas'), ('control_roedores', 'Control de Roedores'), ('otro', 'Otro')], max_length=50)),
                ('mensaje', models.TextField()),
                ('fecha_preferencia', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('contactado', 'Contactado'), ('agendado', 'Agendado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
