# Generated by Django 5.2 on 2025-04-26 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('foto', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInsecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('abreviado', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('idDevice', models.CharField(blank=True, max_length=255, null=True)),
                ('aprobado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Insecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo_insecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.tipoinsecto')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_usuario', models.DateField()),
                ('idTipoCliente', models.IntegerField(blank=True, null=True)),
                ('serial', models.CharField(blank=True, max_length=255, null=True)),
                ('operario', models.BooleanField(default=False)),
                ('hora_ingreso', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('observaciones_tecnicas', models.TextField(blank=True, null=True)),
                ('correctivos', models.TextField(blank=True, null=True)),
                ('firma_operario_tecnico', models.TextField(blank=True, null=True)),
                ('firma_ayudante', models.TextField(blank=True, null=True)),
                ('tipo_servicio', models.CharField(blank=True, max_length=255, null=True)),
                ('objetivo_del_servicio', models.TextField(blank=True, null=True)),
                ('estado_envio', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_orden', models.CharField(blank=True, max_length=255, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.empleado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.usuario')),
            ],
        ),
    ]
