# Generated by Django 5.2 on 2025-04-26 15:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={'ordering': ['-fecha_inicio']},
        ),
        migrations.AddField(
            model_name='empleado',
            name='django_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado_perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insecto',
            name='detalles',
            field=models.TextField(blank=True, help_text='Detalles adicionales sobre el insecto', null=True),
        ),
        migrations.AddField(
            model_name='insecto',
            name='imagen',
            field=models.TextField(blank=True, help_text='URL o datos en base64 de la imagen', null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipoinsecto',
            name='imagen',
            field=models.TextField(blank=True, help_text='URL o datos en base64 de la imagen', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='django_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_externo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado_envio',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='tipo_orden',
            field=models.CharField(blank=True, choices=[('fumigacion', 'Fumigación'), ('control_plagas', 'Control de Plagas'), ('desinfeccion', 'Desinfección'), ('inspeccion', 'Inspección'), ('otro', 'Otro')], max_length=255, null=True),
        ),
    ]
