# Generated by Django 5.2 on 2025-05-23 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('unidad_medida', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='ordenlocativos',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='ordenlocativos',
            name='lugares',
        ),
        migrations.RemoveField(
            model_name='ordenlocativos',
            name='materiales',
        ),
        migrations.AlterField(
            model_name='ordenlocativos',
            name='orden',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='locativo', to='ordenes.orden'),
        ),
        migrations.AlterField(
            model_name='ordenlocativos',
            name='tipo_servicio',
            field=models.CharField(choices=[('INSTALACION', 'Instalación'), ('ARREGLO_LOCATIVO', 'Arreglo locativo')], max_length=20),
        ),
        migrations.CreateModel(
            name='MaterialUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordenes.material')),
                ('orden_locativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_usados', to='ordenes.ordenlocativos')),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('tipos_empresa', models.ManyToManyField(related_name='zonas', to='ordenes.tipoempresa')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenLocativoZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_locativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_zonas', to='ordenes.ordenlocativos')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_zonas', to='ordenes.zona')),
            ],
            options={
                'unique_together': {('orden_locativo', 'zona')},
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='ordenes.zona')),
            ],
            options={
                'unique_together': {('zona', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='ordenlocativos',
            name='zonas',
            field=models.ManyToManyField(related_name='ordenes_locativos', through='ordenes.OrdenLocativoZona', to='ordenes.zona'),
        ),
        migrations.CreateModel(
            name='OrdenLocativoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_areas', to='ordenes.area')),
                ('orden_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_areas', to='ordenes.ordenlocativozona')),
            ],
            options={
                'unique_together': {('orden_zona', 'area')},
            },
        ),
    ]
