# Generated by Django 5.2 on 2025-05-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_material_remove_ordenlocativos_areas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='tipo',
            field=models.CharField(choices=[('ORDEN_SERVICIO', 'Orden de Servicio'), ('INSPECCION', 'Inspección General'), ('SACRIFICIO', 'Inspección Planta Sacrificio'), ('SERVICIOS_LOCATIVOS', 'Servicios Locativos')], max_length=50),
        ),
    ]
