# Generated by Django 4.2 on 2025-05-24 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_alter_orden_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPlagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría de Plaga',
                'verbose_name_plural': 'Categorías de Plagas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Área', 'verbose_name_plural': 'Áreas'},
        ),
        migrations.AlterModelOptions(
            name='desinfeccionambientes',
            options={'verbose_name': 'Desinfección de Ambientes', 'verbose_name_plural': 'Desinfecciones de Ambientes'},
        ),
        migrations.AlterModelOptions(
            name='inspecciongeneral',
            options={'verbose_name': 'Inspección General', 'verbose_name_plural': 'Inspecciones Generales'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
        migrations.AlterModelOptions(
            name='materialuso',
            options={'verbose_name': 'Material Uso', 'verbose_name_plural': 'Materiales Usados'},
        ),
        migrations.AlterModelOptions(
            name='orden',
            options={'verbose_name': 'Orden', 'verbose_name_plural': 'Órdenes'},
        ),
        migrations.AlterModelOptions(
            name='ordenlocativoarea',
            options={'verbose_name': 'Orden Locativo Área', 'verbose_name_plural': 'Órdenes Locativos Áreas'},
        ),
        migrations.AlterModelOptions(
            name='ordenlocativos',
            options={'verbose_name': 'Orden Locativo', 'verbose_name_plural': 'Órdenes Locativos'},
        ),
        migrations.AlterModelOptions(
            name='ordenlocativozona',
            options={'verbose_name': 'Orden Locativo Zona', 'verbose_name_plural': 'Órdenes Locativos Zonas'},
        ),
        migrations.AlterModelOptions(
            name='zona',
            options={'verbose_name': 'Zona', 'verbose_name_plural': 'Zonas'},
        ),
        migrations.RemoveField(
            model_name='inspecciongeneral',
            name='especie_encontrada',
        ),
        migrations.CreateModel(
            name='Plaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('nivel_riesgo', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], default='MEDIO', max_length=20)),
                ('habitat_comun', models.TextField(blank=True)),
                ('metodo_control', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='plagas/')),
                ('activa', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especies', to='ordenes.categoriaplagas')),
            ],
            options={
                'verbose_name': 'Plaga',
                'verbose_name_plural': 'Plagas',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='inspecciongeneral',
            name='especies_encontradas',
            field=models.ManyToManyField(blank=True, related_name='inspecciones', to='ordenes.plaga', verbose_name='Especies encontradas'),
        ),
    ]
