# Generated by Django 5.1.7 on 2025-06-15 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_categoriaplagas_alter_area_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Sección / Categoría')),
                ('descripcion', models.TextField(blank=True, help_text='(opcional) Descripción breve de la sección', null=True)),
            ],
            options={
                'verbose_name': 'Sección / Categoría',
                'verbose_name_plural': 'Secciones / Categorías',
            },
        ),
        migrations.CreateModel(
            name='AspectoLocativoHigiene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vias_acceso_cerradas', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NA', 'No Aplica')], default='NA', max_length=2, verbose_name='Vías de acceso bien cerradas')),
                ('paredes_sin_grietas', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NA', 'No Aplica')], default='NA', max_length=2, verbose_name='Estado de paredes sin grietas')),
                ('condiciones_orden_aseo', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NA', 'No Aplica')], default='NA', max_length=2, verbose_name='Buenas condiciones de orden y aseo')),
                ('basuras_con_tapa', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NA', 'No Aplica')], default='NA', max_length=2, verbose_name='Basuras con tapa y evacuadas permanentemente')),
                ('luz_puertas_menor_1cm', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NA', 'No Aplica')], default='NA', max_length=2, verbose_name='Luz en puertas menor a 1 cm')),
                ('techos_buen_estado', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NA', 'No Aplica')], default='NA', max_length=2, verbose_name='Techos en buen estado')),
                ('pisos_media_cana_sin_grieta', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NA', 'No Aplica')], default='NA', max_length=2, verbose_name='Pisos con media caña y sin grieta')),
                ('ventana_proteccion_malla', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NA', 'No Aplica')], default='NA', max_length=2, verbose_name='Ventana con protección malla')),
                ('presencia_grasa', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NA', 'No Aplica')], default='NA', max_length=2, verbose_name='Presencia de grasa')),
                ('manejo_basuras_adecuado', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NA', 'No Aplica')], default='NA', max_length=2, verbose_name='Manejo de basuras adecuado')),
                ('exteriores_limpios_sin_basura', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NA', 'No Aplica')], default='NA', max_length=2, verbose_name='Exteriores limpios sin basuras y adecuado control de maleza')),
                ('estibacion_conserva_espacio', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NA', 'No Aplica')], default='NA', max_length=2, verbose_name='La estibación: conserva espacio contra la pared y permite las labores de aseo y control de plagas')),
                ('rejillas_desague_pisos', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NA', 'No Aplica')], default='NA', max_length=2, verbose_name='Rejillas: para correcto desague de pisos')),
                ('paredes_pisos_limpios', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NA', 'No Aplica')], default='NA', max_length=2, verbose_name='Paredes y pisos limpios y buenos')),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aspecto_locativo_higiene', to='ordenes.orden')),
            ],
            options={
                'verbose_name': 'Aspecto Locativo e Higiene',
                'verbose_name_plural': 'Aspectos Locativos e Higiene',
            },
        ),
        migrations.CreateModel(
            name='ItemCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Item')),
                ('respuesta', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('NA', 'N/A')], max_length=3, verbose_name='Respuesta')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordenes.categoria', verbose_name='Sección / Categoría')),
            ],
        ),
    ]
