# Generated by Django 5.2 on 2025-06-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_categoriaplagas_alter_area_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenlocativos',
            name='especies',
            field=models.ManyToManyField(blank=True, related_name='ordenes_locativas', to='ordenes.plaga'),
        ),
    ]
