# Generated by Django 4.2 on 2025-06-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_categoria_aspectolocativohigiene_itemcategoria'),
        ('ordenes', '0005_ordenlocativos_especies'),
    ]

    operations = [
    ]
