# Generated by Django 5.2 on 2025-06-17 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0006_merge_20250615_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaLocativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Área Locativa',
                'verbose_name_plural': 'Áreas Locativas',
            },
        ),
        migrations.CreateModel(
            name='Higiene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Higiene',
                'verbose_name_plural': 'Higienes',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('ingrediente_activo', models.CharField(max_length=200)),
                ('dosificacion', models.CharField(max_length=100)),
                ('fecha_vencimiento', models.DateField()),
                ('ultimo_lote', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicio',
            },
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_control', models.PositiveIntegerField(editable=False)),
                ('fechadelservicio', models.DateTimeField(editable=False)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('recomendaciones', models.TextField(blank=True, verbose_name='Recomendaciones')),
                ('firma_operario', models.ImageField(blank=True, null=True, upload_to='firmas/', verbose_name='Firma Operario')),
                ('firma_acompanante', models.ImageField(blank=True, null=True, upload_to='firmas/', verbose_name='Firma Acompañante')),
                ('certificado', models.FileField(blank=True, null=True, upload_to='certificados/', verbose_name='Certificado')),
                ('areaslocativas', models.ManyToManyField(blank=True, related_name='ordenes_servicio', to='ordenes.arealocativa', verbose_name='Áreas Locativas')),
                ('especies', models.ManyToManyField(blank=True, related_name='ordenes_servicio', to='ordenes.plaga', verbose_name='Especies')),
                ('higiene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordenes.higiene', verbose_name='Higiene')),
                ('orden_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='ordenes.orden')),
            ],
            options={
                'verbose_name': 'Orden de Servicio',
                'verbose_name_plural': 'Órdenes de Servicio',
            },
        ),
        migrations.CreateModel(
            name='OrdenServicioZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas_servicio', to='ordenes.ordenservicio')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas_servicio', to='ordenes.zona')),
            ],
            options={
                'verbose_name': 'Zona en Orden de Servicio',
                'verbose_name_plural': 'Zonas en Órdenes de Servicio',
                'unique_together': {('orden_servicio', 'zona')},
            },
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='zonas',
            field=models.ManyToManyField(related_name='ordenes_servicio', through='ordenes.OrdenServicioZona', to='ordenes.zona', verbose_name='Zonas'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='ordenes_servicio', to='ordenes.producto', verbose_name='Productos'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordenes.tiposervicio', verbose_name='Tipo de Servicio'),
        ),
        migrations.AlterUniqueTogether(
            name='ordenservicio',
            unique_together={('orden_principal', 'numero_control')},
        ),
    ]
