# Generated by Django 5.2 on 2025-06-17 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0007_arealocativa_higiene_producto_tiposervicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecieUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], max_length=10)),
                ('orden_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.ordenservicio')),
                ('plaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.plaga')),
            ],
        ),
        migrations.CreateModel(
            name='HigieneUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], max_length=10)),
                ('higiene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.higiene')),
                ('orden_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.ordenservicio')),
            ],
        ),
        migrations.DeleteModel(
            name='AspectoLocativoHigiene',
        ),
    ]
